### ISSUE TITLE
Lib broken?

### ISSUE THREAD

**Issue by Bertus-W** [stormgbs/cron-rs#1]
lib.rs is empty, no imports. i don't know how to use it if there are no imports. I see in your commit that you moved everything into different files. But everything is not usable. You should write tests to confirm your library is fully working.

**Comment by stormgbs** [comment]
@TheUberCatman  I am sorry for my poor README,  package cron-rs is placed on [cargo crates](https://crates.io/crates/cron_rs) currently.  One example can be found in src/main.rs. I will fix the issue you mentioned, and add usage about running a job this week. Thx.

**Comment by Bertus-W** [comment]
@stormgbs, a library shouldn't use a main.rs. you need to make all the objects a user can use public in your lib.rs

**Comment by stormgbs** [comment]
@TheUberCatman  Yes, you are right, I'll fix it :)

**Comment by Bertus-W** [comment]
you also have a file in your repository that doesn't belong there, it's called `.cz-config.js`. You might want to put your source files into modules too.

**Comment by stormgbs** [comment]
It is a config of  [git commitizen tool](https://github.com/leonardoanalista/cz-customizable) for more gracefull git commit message.

**Comment by stormgbs** [comment]
@TheUberCatman  I have fixed all problems. The lastest version is 0.1.6 . I have moved main.rs to examples directory, completed lib.rs, rewrite README and so on. Also, I have tested it, you could checkout the lastest code now.  Tell me if you have other issues, and you can create PRs, I am very gland to accept it.
